### ISSUE TITLE
Please recommend Haskell Platform for Windows users

### ISSUE THREAD

**Issue by hugoestr** [bitemyapp/learnhaskell#103] opened 2016-04-15 23:02 UTC
Haskell stack seems cool. It is not ready in Windows at this point, though.  Too many exceptions. It is too easy to make a mistake and to have to troubleshoot errors that involve digging in app_data/roaming and windows versions of git.  For learning, the Haskell Platform is probably an easier install for Windows users at this point. You can always recommend to look into stack once they are ready to build real applications.

Is this is too much to ask, then at least recommend that Windows users install ubuntu on a VM or run it on AWS. 

Bash for Windows is supposed to come out this summer. Once it comes out it will be a matter of telling Windows users to use that instead of installing windows compiled binaries.

**Comment by hasufell** [comment] 2016-10-15 11:42
The whole "don't use haskell platform" is rather opinionated anyway and should be removed. Just add a note about what stack is.

**Comment by bitemyapp** [comment] 2016-10-15 18:54
Could you clarify on the problems? Stack had a couple devs working full-time on Windows when it was written to avoid an accumulation of problems.

I don't know any unhappy `Stack <> Windows` users and they usually recommend other Windows users to use the same.

**Comment by bitemyapp** [comment] 2016-10-15 18:56
Also if you have filed any relevant bugs with http://github.com/commercialhaskell/stack -- please link them here.

**Comment by dagit** [comment] 2016-10-15 23:03
> Bash for Windows is supposed to come out this summer. Once it comes out it will be a matter of telling Windows users to use that instead of installing windows compiled binaries.

Unfortunately Bash for Windows doesn't yet support all the system calls GHC needs. My understanding is that MS wants to add support for everything but they wanted to get it out to people sooner instead of later.

**Comment by Andrew-Webb** [comment] 2016-12-12 11:31
> I don't know any unhappy Stack <> Windows users

Enthused by the Haskell Book, and not having a Mac or Linux, I installed Stack on my Windows 8.1 machine.  Right away there was inconsistency between the docs and the Stack installer (and between different parts of the Stack installer) about what was the "stack root" folder... should it be C:\sr or C:\stack_root or somewhere under my appData\Roaming folder?

Having sorted that out  (maybe; who knows?) I invoked `stack ghci` and it attempted to install a whole scad of stuff, and then ground to a halt with this error:-
https://github.com/commercialhaskell/stack/issues/1798

Other people currently have this error, but yet the issue about it is currently **Closed**.

I sighed, reflected on the fact that I _knew_ this would happen (it always does when the installing docs warn of "issues" and "workarounds" wrt Windows), uninstalled and walked away.

Stack ain't ready on Windows... and I wonder if the Haskell Platform is too....   it would come as absolutely no surprise to me if I had endless silly and difficult issues on the Haskell Platform as well.  I don't know if I can be bothered to try.

Purescript, on the other hand, installs very nicely and easily via npm.  Maybe I'll use the Haskell Book as a conduit to learning Purescript, and leave Haskell until I can get a Linux machine or a Mac.

**Comment by bitemyapp** [comment] 2016-12-12 19:02
>Other people currently have this error, but yet the issue about it is currently Closed.

Right but nobody's getting them a repro to work with. You yourself bailed before anybody could investigate it with you.

That error isn't common for Haskell / gcc specifically, but usually when it happens in Windows you have registry references to drive letters that have since disappeared.

I'm closing this as it appears to be turning into a dumping ground.

**Closed by bitemyapp** 2016-12-12 19:02 UTC

**Comment by Andrew-Webb** [comment] 2016-12-13 08:56
> Right but nobody's getting them a repro to work with. You yourself bailed before anybody could investigate it with you

If the Stack people are interested in solving this problem, and ask me nicely, I'd be happy to try again, and answer any questions that they have.

> I'm closing this as it appears to be turning into a dumping ground

It seems to me to be a small but significant accumulation of anecdotal evidence that maybe the creator of this issue has a point.

--

See it from my point of view...  I work/play exclusively on Windows.  On Windows, installers "just work".  If some technology can't get its installer to work (a rare case), long experience has taught me that many, many other problems will follow and plague me forever, even if I do manage to get it to install somehow.

So....

Day 0 - I am enthused by Mr. Allen and Ms. Moronuki to try Haskell.
Day 1 - I attempt to install Haskell via Stack, as recommended.  Warning bells sound when I look at Stack's website re. Windows installation.  Alarm bells sound when I detect conflicting information on the location of 'stack root'.  Post-installation setup fails with a malware-style modal popup that doesn't cancel even though it has a Cancel button.
Day 2 - I report the problem in two obvious places on GH.  No reply from Stack.  A dismissive reply from you.

What conclusions should I draw from this?  Frankly my conclusion right now is that I have stepped into a world where Windows isn't really a nice platform for learning Haskell.  I could fight issues, build repros, don my thick skin to cope with dismissive responses (but at least it was a response), when all I really want to do (and have time for) is learn Haskell...!

Right now, I think that what the future holds for me is PureScript,, not Haskell.

**Comment by hugoestr** [comment] 2016-12-13 16:51
I forgot about this issue  :)

I will try Haskell Stack again and see if it is better now than it was back in April.

As for my initial issue, it was meant in a non-judgmental helpful manner. I came to this repo after listening to a podcast where you were talking about your book on Haskell. You said that you welcome any feedback, so that is why I created this issue. 

If the goal is to get people to learn and adopt Haskell, avoiding installation problems is important. People will move on from a technology if it becomes too hard to even get it running. Especially when you have a limited amount of time to dedicate to new technologies.

If stack is the superior way to run Haskell, why not suggest a VM or Docker in windows? This will save people time. Once they have bought into the language, then those bug reports to stack on windows will happen because they are committed to the language and to the platform. 

Thanks again for putting this site together. Thanks again for writing your book. Hopefully it is the one that can bring more people into such a beautiful language. :)

**Comment by dagit** [comment] 2016-12-13 19:15
@Andrew-Webb In my experience, the Haskell Platform works pretty well on Windows these days. That's how I install Haskell on Windows. With that said, I hope you enjoy PureScript. It's a nice language with passionate developers.

When/If you decide to try Haskell again, I encourage you to try it on Linux, even if that means you need to put up with a virtual machine. Maybe just long enough to follow some basics learning materials and then switch to a Windows-only setup once you're more familiar with it.

**Comment by bitemyapp** [comment] 2016-12-13 19:35
@dagit Did y'all release a fixed version of Stack in the Platform installer yet or is it still broken?

I think one of the concerns Michael had about y'all packaging Stack with Platform is that something wouldn't work and then you'd drag your feet on fixing it.

**Comment by dagit** [comment] 2016-12-13 21:32
@bitemyapp What fix did you have in mind? Maybe link an issue?

**Comment by bitemyapp** [comment] 2016-12-14 03:28
@dagit https://github.com/haskell/haskell-platform/issues/251

**Comment by hvr** [comment] 2016-12-14 09:21
@bitemyapp 

> @dagit Did y'all release a fixed version of Stack in the Platform
> installer yet or is it still broken?

That's an unnecessarily snarky remark. But let's quickly review the time-line of the relevant events involved:

- 2016-08-30 : Michael files the referenced issue HP #251, Gershom and Michael start discussing how to resolve this

- 2016-09-01 : Gershom implements a fix, and submits it as https://github.com/commercialhaskell/stack/pull/2552 where it gets instantly approval by Michael

- 2016-09-06 : Emanuel merges the PR            

- 2016-12-12 : Over three months later(!), Stack 1.3.0 gets released, which according to Git is the first Stack release to incorporate the fix https://github.com/commercialhaskell/stack/commit/2ca50de99f321e63e60ac4c1b1a5bdd170eb5033

> I think one of the concerns Michael had about y'all packaging Stack
> with Platform is that something wouldn't work and then you'd drag your
> feet on fixing it.

You seem to be having a personal issue with the HP project and/or its maintainers. It's quite frustrating to see you spreading FUD about the HP, especially when the facts tell the exact opposite story ;-(

**Comment by Andrew-Webb** [comment] 2016-12-14 09:57
@dagit 

> the Haskell Platform works pretty well on Windows these days. That's how I install Haskell on Windows.

Thanks, I will try that.

> I encourage you to try it on Linux, even if that means you need to put up with a virtual machine

Happy to do it, esp. with the holiday period coming up.

My end goal is PureScript, since there is no chance of using Haskell at work, whereas what I use to generate JavaScript is more or less up to me.  (I know there is `ghcjs`, but PureScript seems a better fit to me.)  My plan of action is to work through [The Haskell Book](http://haskellbook.com/) with genuine Haskell - i.e. learn from the 'Ur text' as it were - and then switch to the derivative that is PureScript.  If I started with PureScript and never looked seriously at Haskell, I would always be wondering about it...

**Comment by hasufell** [comment] 2016-12-14 15:10
> You seem to be having a personal issue with the HP project and/or its maintainers. It's quite frustrating to see you spreading FUD about the HP, especially when the facts tell the exact opposite story ;-(

I'd go so far to say he's deliberately spreading misinformation for political reasons. There is no community consensus about which option is "better". Some prefer HP, others stack. This can also be observed by repeatedly upcoming discussions about that topic in `#haskell`. Linking to an opinionated post doesn't reflect the "community opinion", which can basically be summarized as "just try both". There are also largely varying opinions on how "simple" stack really is. And that's not surprising, since that's always the case with software and subjective usability.

Also, I'm pretty disappointed in this project. It should give correct and non-biased information without partaking in the stack vs HP war, since it's a commonly linked resource in `#haskell`. Just inform users of their valid options.

**Comment by vincenthz** [comment] 2016-12-14 15:51
> Some prefer HP, others stack

This frame the problem with the whole discourse: this is not about random people preferences. It's about a reasonable choice for who is targeted by the book.

**Comment by snoyberg** [comment] 2016-12-14 20:05
Since there's a lot of misinformation coming from brigaders:

* I reported in September of *2015* the changes needed to make the planned HP+Stack setup work. It was released without those changes being implemented: https://github.com/haskell/haskell-platform/issues/207 and https://github.com/haskell/haskell-platform/issues/251#issuecomment-243340069
* I explicitly stated that HP should ship a patched version of Stack instead of requiring crazy command line parameters or waiting for an official release to include the patch https://github.com/haskell/haskell-platform/issues/251#issuecomment-243340871
* The HP+Stack setup has been problematic and has wasted the time of Stack maintainers and users. The problems it introduces do not exist with Stack on its own, and the HP installer - for a Stack user - adds nothing of value at all http://stackoverflow.com/questions/40961963/haskell-cabal-c-compiler-cannot-create-executables#comment69138223_40961963
* Users are being actively told to use Stack with an HP install despite the fact that this is known to be broken https://www.reddit.com/r/haskell/comments/5h4wxf/trouble_with_installing_compiler/day35vm/

As to the original bug report here: I agree with @bitemyapp, an issue should be opened if there are actually Windows bugs affecting people. Regarding the only actual bug report referenced here (https://github.com/commercialhaskell/stack/issues/1798): yes, that looks like a real bug that should be fixed, and reading that issue I only see positive comments from everyone involved towards trying to either fix or mitigate the issue. There is no indication that the issue was ignored, but simply that the users reporting the issue were no longer troubled by it, and therefore trying to find a solution would not be possible (due to lack of any kind of reproducing test case).

**Comment by hasufell** [comment] 2016-12-15 19:50
> This frame the problem with the whole discourse: this is not about random people preferences. It's about a reasonable choice for whom this book target.

If you are referring to the __non-free__ book... that has its own web-site and this site is largely linked because of the __free__ reccomendations. And I don't see those depending on stack in any way or it being the only reasonable choice.
